#' Print validation information
#'
#' This is a method of the [print()] function for object
#'  of class `validation` generated from [validateData()].
#'
#' Print on the command line interface all validation information on:
#'  * The presence of appropriate column names
#'  * Duplicated people, groups and locations ids
#'  * PIDs in people, groups and relations tables not in locations table
#'  * Nodes in relations tables
#'  * Group size
#'
#' @param x Object generated by [validateData()]
#' @param ... Only used to remain consistent with plot generic function
#'
#' @return NULL
#'
#' @export
print.validation <- function(x, ...){

    # Column names information
    messageColumns(x$details$columns)

    # Duplicated IDs
    messageCount(x$duplicated_ids, "Duplicated ids")

    # PIDs in locations
    messageCount(x$pids_locations, "PIDs not in locations table")

    # Relation IDs
    messageRelations(x$freq_relations$relative)

    # Group size
    messageGroups(x$group_size)

    # Return nothing
    return(NULL)
}

#' Print partial validation information
#'
#' This is a method of the [print()] function for object
#'  of class `partial.validation` generated from [validateData()].
#'
#' Print on the command line interface validation information on
#'  column names only. Other validation could not be compute.
#'
#' @param x Object generated by [validateData()] for which columns are not valid
#' @param ... Only used to remain consistent with plot generic function
#'
#' @return NULL
#' 
#' @export
print.partial.validation <- function(x, ...){

    # Columns output
    messageColumns(x$details$columns)

    # Partial error
    cli::cli_div(theme = list (.alert = list(color = "red")))
    cli::cli_alert("Validation stoped")
    cli::cli_end()
    cat("Either missing variables or wrong column names", "\n")

    # Return nothing
    return(NULL)
}

#' Print column name validation
#'
#' Internal functioncalled by [print.validation()]
#'
#' @param v_col details$columns from [validateData()]
#'
#' @return NULL
#' 
#' @noRd
messageColumns <- function(v_col) {

    # Define theming
    cli::cli_div(theme = list(span.success = list(color = "green"),
                              span.fail = list(color = "red")))

    # Create header
    cli::cli_h1("Column names")

    # Function to print Line
    cliPrintLine <- function(name){

        # Print table name
        cli::cli_text(paste0("{.strong ", name, "}"))

        # Extract column names
        col_names <- names(v_col[[name]])

        # Transform validation message
        msg <- lapply(col_names, function(x){
            ifelse(v_col[[name]][x],
                paste("{.success v}", x),
                paste("{.fail x}", x))
        }) |> unlist()

        # Print column validation
        cli::cli_text(paste(msg, collapse = " | "))
    }

    # print output for every table
    cliPrintLine("locations"); cli::cli_text()
    cliPrintLine("people"); cli::cli_text()
    cliPrintLine("groups"); cli::cli_text()
    cliPrintLine("relations")

    # Return nothing
    return(NULL)
}

#' Print count information
#'
#' Internal function called by [print.validation()]. 
#' Consider success values > 0, and failed != 0.
#'
#' @param list_data Count data
#' @param header String displayed in CLI
#'
#' @return NULL
#'
#' @noRd
messageCount <- function(list_data, header){

    # Define theming
    cli::cli_div(theme = list(span.success = list(color = "green"),
                              span.fail = list(color = "red")))

    # Create header
    cli::cli_h1(header)

    # Number by table
    for(x in names(list_data)) {

        if(list_data[[x]] == 0) {
            cli::cli_text("{x}: {.success {list_data[[x]]}}")
        } else {
            cli::cli_text("{x}: {.fail {list_data[[x]]}}")
        }
    }

    # Return nothing
    return(NULL)
}

#' Print group validation information.
#'
#' Internal function called by [print.validation()]
#'
#' @param group_data Count data
#'
#' @return NULL Print validation information on CLI
#'
#' @noRd
messageGroups <- function(group_data){

    # Define theming
    cli::cli_div(theme = list(span.success = list(color = "green"),
                              span.fail = list(color = "red")))

    # Calculate number of group <= 0
    count <- sum(group_data$size_no_ind <= 0)

    # Header
    cli::cli_h1("Group size")

    # Print message
    if(count == 0) {
            cli::cli_text(
                "{.success {count}} groups have a size <= 0")
        } else {
            cli::cli_text(
                "{.fail {count}} groups have a size <= 0"
            )
        }

    # Return nothing
    return(NULL)
}

#' Print information on relation validation
#'
#' Internal function called by [print.validation()]
#' 
#' @param relative_freqs Relative frequencies generated by [validateRelations()]
#'
#' @return NULL
#'
#' @noRd
messageRelations <- function(relative_freqs){

    # Define theming
    cli::cli_div(theme = list(span.success = list(color = "green"),
                              span.fail = list(color = "red")))

    # Extract non zero frequencies
    relative_non_zero <- lapply(relative_freqs, function(x) {

        # Extract position
        index <- which(x > 0, arr.ind = TRUE)

        # Extract values
        out <- t(apply(index, 1, function(y) {
            c(id = colnames(x)[y["col"]],
              val = x[y["row"], y["col"]])
            }
        ))

        # Add mpde as first line
        out <- cbind(rownames(out), out)
        colnames(out)[1] <- "node"
        rownames(out) <- NULL

        # Return
        return(out)
    })

    # Header
    cli::cli_h1("Node id frequencies in relation table")

    # Function to print a single line
    cliPrintLine <- function(val, node, id){

        # Round value
        val <- round(val, 2)

        # Print
        if(val == 100){
                cli::cli_text("{.success {val}%} of {node} is in {id}")
            } else {
              cli::cli_text("{.fail {val}%} of {node} is in {id}")
            }
    }


    # Function to print multiple lines
    cliPrint <- function(tbl) {

        for(i in seq(nrow(tbl))){

            # Extract
            val <- as.numeric(tbl[i, "val"]) * 100
            node <- tbl[i, "node"]
            id <- tbl[i, "id"]

            # Print
            cliPrintLine(val, node, id)
        }
    }

    # Print People
    cli::cli_text("{.strong People relations}")
    cliPrint(relative_non_zero[[1]])
    cli::cli_text()

    # Print groups
    cli::cli_text("{.strong Group relations}")
    cliPrint(relative_non_zero[[2]])
    cli::cli_text()

    # Print locations
    cli::cli_text("{.strong Location relations}")

    ## Print location
    location_val <- relative_freqs[[3]][2, 1] * 100
    cliPrintLine(location_val, "node_2", "location_id")

    ## Sum people an group ids
    social_val <- sum(relative_freqs[[3]][1, 2:3]) * 100
    cliPrintLine(social_val, "node_1", "people_id or group_id")
}