#' Summarize veritas data information
#' 
#' @param veritas_all Object generated by [transformData()]
#' 
#' @return NULL print on CLI summary information
summary.veritas.split <- function(veritas_split){

    # Extract count
    nb_participants <- length(veritas_split)
    nb_locations <- attr(veritas_split, "nb_locations")
    nb_people <- attr(veritas_split, "nb_people")
    nb_groups <- attr(veritas_split, "nb_groups")
    nb_relations <- attr(veritas_split, "nb_relations")

    # Print summary
    cli::cli_text("{nb_participants} participants")
    cli::cli_text("{nb_locations} locations")
    cli::cli_text("{nb_people} people")
    cli::cli_text("{nb_groups} groups")
    cli::cli_text("{nb_relations} relations")
}

#' Summarize veritas data information for a single PID
#'
#' @param veritas_pid Single object from the
#' list the generated by [transformData()]
#'
#' @return NULL print on CLI summary information
summary.veritas.pid <- function(veritas_pid){

    # Extract pid
    pid <- veritas_pid$locations$pid

    # Extract count
    nb_locations <- length(veritas_pid$locations$location_id)
    nb_people <- length(veritas_pid$people$people_id)
    nb_groups <- length(veritas_pid$groups$group_id)

    if(!is.null(veritas_pid$relations)) {

    nb_relations_people <- veritas_pid$relations |>
                                subset(relation_type == 1) |>
                                nrow()

    nb_relations_groups <- veritas_pid$relations |>
                                subset(relation_type == 2) |>
                                nrow()

    nb_relations_locations <- veritas_pid$relations |>
                                subset(relation_type == 3) |>
                                nrow()

    } else {
        nb_relations_people <- 0
        nb_relations_groups <- 0
        nb_relations_locations <- 0
    }

    # Print
    cli::cli_h2("nodes")
    cli::cli_text("{nb_locations} locations")
    cli::cli_text("{nb_people} people")
    cli::cli_text("{nb_groups} groups")

    cli::cli_h2("relations")
    cli::cli_text("{nb_relations_people} people <--> people")
    cli::cli_text("{nb_relations_groups} people <--> group")
    cli::cli_text("{nb_relations_locations} people/group <--> locations")
}