#' Summarize validation information
#'
#' This function report if each validation test pass of fail.
#'
#' This is a method of the [summary()] generic function.
#'  Print on the Command Line Interface pass or fail for each validation test
#'
#' @param object Object of class `validation` generated by [validateData()]
#' @param ... Only used to remain consistent with plot generic function
#'
#' @return NULL
#'
#' @export
summary.validation <- function(object, ...){

    # Define theming
    cli::cli_div(theme = list(span.success = list(color = "green"),
                              span.fail = list(color = "red")))

    # Function to print line
    cliPrintLine <- function(name, status){

        # Create
        if(status == TRUE){
            status_txt <- paste0("{.success pass}")
        } else {
            status_txt <- paste0("{.fail fail}")
        }

        # Print
        cli::cli_text(paste0("{.strong ", name, ": }", status_txt))
    }

    # Extract detail
    details <- object$details

    # Print each line
    cliPrintLine("Column names", all(unlist(details$columns)))
    cliPrintLine("Duplicated IDs", details$dupli_ids)
    cliPrintLine("PIDs in locations", details$pids_locations)
    cliPrintLine("Relation table", all(unlist(details$relations)))
    cliPrintLine("Group size", details$group_size)

    # Return nothing
    return(NULL)
}

#' Summarize partial validation information
#'
#' This function report that column names fail, and the other validation
#'  are unknown since they could not be test in absence of proper
#'  column names
#'
#' This is a method of the [summary()] generic function.
#'  Print on the Command Line Interface pass or unknown for each validation
#'  test
#'
#' @param object Object of class `partial.validation`
#'  generated by [validateData()]
#' @param ... Only used to remain consistent with plot generic function
#'
#' @return NULL
#'
#' @export
summary.partial.validation <- function(object, ...){

    # Define theming
    cli::cli_div(theme = list(span.unknow = list(color = "yellow"),
                              span.fail = list(color = "red")))

    # Print
    cli::cli_text("{.strong Column names:} {.fail fail}")
    cli::cli_text("{.strong Duplicated IDs:} {.unknow unknown}")
    cli::cli_text("{.strong PIDs in locations:} {.unknow unknown}")
    cli::cli_text("{.strong Relation table:} {.unknow unknown}")
    cli::cli_text("{.strong Group size:} {.unknow unknown}")

    # Return nothing
    return(NULL)
}
